name: Publish Docker Image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log message
        run: echo Starting Job!

      - name: Build the Docker image
        run: |
          echo Logging into docker,
          docker login -u amanryder -p ${{ secrets.GH_TOKEN }} ghcr.io
          echo Building Image.
          docker build -t ghcr.io/amanryder/rdas-analytics:latest .

      - name: Push the Docker image
        run: |
          echo Pushing Image.
          docker push ghcr.io/amanryder/rdas-analytics

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: install ssh keys
  #       run: |
  #         install -m 600 -D /dev/null ~/.ssh/rdas_id_rsa
  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/rdas_id_rsa
  #         ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

  #     - name: deploy
  #       run: |
  #         ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} ". redeploy_rdas.sh"

  #     - name: cleanup
  #       run: rm -rf ~/.ssh
